server:
  port: 8080
  error:
    include-stacktrace: ON_PARAM
#this will remove the stack trace from enpoint response if there's an exception
#by default it stays as ALWAYS
spring:
  profiles:
    active: qa

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: dev
welcome:
  message: Welcome from dev
domain:
  url: http://localhost:8080
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    initialization-mode: always
#    added to run data.sql on load
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome from QA
domain:
  url: http://localhost:8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: prod
welcome:
  message: Welcome from PROD
domain:
  url: http://localhost:8080