server:
  port: 8080

spring:
  profiles:
    active: qa

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev
welcome:
  message: Welcome from dev
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome from QA

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: Welcome from PROD